### ISSUE TITLE
Crear excel horas trabajadas 

### ISSUE THREAD

**Issue by alvarroo** [srodriguez1301/2024-ISO2-C02#1]
Necesitamos crear un excel de la imputadas, que actualizaremos cada semana con las horas trabajadas.  
Hemos nombrado como responsable de el excel a Raul que se encargara de subir el excel cada semana después de cada reunión. 
Le ayudaremos en el recuento de la las horas trabajadas para llevar un excel preciso y con el desempeño de cada integrante en cada reunión así como expertos en cada areas como los de github, secretarios o coordinadores.

**Comment by alvaromozos12** [comment]
Al final de la reunión, @rmataUCLM04 creo y subió el excel de las horas trabajadas #doc/Excel Horas Trabajadas/Horas Trabajadas.xlsx

**Comment by alvarroo** [comment]
Al final de la reunión, @rmataUCLM04 creo y subió el excel de las horas trabajadas #doc/Excel Horas Trabajadas/Horas Trabajadas.xlsx
