### ISSUE TITLE
Añadir a la wiki Caracteristicas de calidad y gestion de Configuración

### ISSUE THREAD

**Issue by alvarroo** [srodriguez1301/2024-ISO2-C02#18]
Tras la realización de el trabajo teórico vamos a incluir lo realizado en la wiki

**Comment by alvarroo** [comment]
Incluido ya tres caracteristicas de calidad a la documentación de la wiki

**Comment by Manuel-Villanueva-Alises** [comment]
Incluido ya la gestión de configuración a la documentación de la wiki
