### ISSUE TITLE
 casos de uso y ánalisis de requisitos de la interacción 0

### ISSUE THREAD

**Issue by srodriguez1301** [srodriguez1301/2024-ISO2-C02#6]
He subido en la carpeta doc los casos de uso y el analisis de requisistos de la interacción 0, tambien en la tabla kanban he movido la tarea de analisis de requisitos de it 0 a 'hecho'.

**Comment by rmataUCLM04** [comment]
Mañana en la reunion programada se revisara con los expertos en Git

**Comment by srodriguez1301** [comment]
Ya he modificado ambos documentos, estan bien subidos con los cambios dichos en la reunion en la carpeta 'doc'.
